# configs/config.yaml

defaults:
  - _self_  # Include the base configuration itself
  - experiment: experiment1  # Default experiment

# General model settings
model:
  hidden_dim: 64  # Default hidden dimension

# General training settings
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 2

# Data settings
data:
  root: ${hydra:runtime.cwd}/data  # Store data relative to the working directory

# Prevent Hydra from changing the working directory
hydra:
  run:
    dir: .
