defaults:
  - _self_  # Ensures this file’s content is processed before any overrides
  - experiments: experiment1

dagshub:
  repo_owner: "MarkNZed" #dagshub username
  repo_name: "GPT-NeoX-Colab"

# Base settings
output_dir: ../outputs
experiment_name: "TBD"
seed: 42

# General model settings
model:
  hidden_dim: 64  # Default hidden dimension

# General training settings
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 2

# Data settings
data:



