# Parameters used for text generation
{
  # Text gen type: `input-file`, `unconditional` or `interactive`
  "text_gen_type": "unconditional",

  # Params for all
  "maximum_tokens": 102,
  "prompt_end": "\n",
  "temperature": 1.0,
  "top_p": 0.0,
  "top_k": 0,
  "recompute": false,

  # `unconditional`: samples
  "num_samples": 10,

  # input/output file
  "sample_input_file": "sample_input.txt",
  "sample_output_file": "sample_output.txt",

  "data_path": "processed_data/tinyshakespeare_text_document",

  "save": "checkpoints",
  "load": "checkpoints",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard_dir": "tensorboard_gen",
  "log_dir": "logs_gen",
}