{
  "pipe_parallel_size": 0, # Because running on one GPU
  "model_parallel_size": 0, # Because running on one GPU

  # model settings
  "num_layers": 4,
  "hidden_size": 256,
  "num_attention_heads": 4,
  "seq_length": 512,
  "max_position_embeddings": 512,
  "pos_emb": "rotary",
  "no_weight_tying": false, # Sharing embedding and output weights
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",

  "scaled_upper_triang_masked_softmax_fusion": false,
  "bias_gelu_fusion": false,
  "rope_fusion": false,
  "layernorm_fusion": false,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.001,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 0.0001,

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },

  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 1,
  "data_impl": "mmap",
  "num_workers": 1,

  # activation checkpointing
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  # precision settings
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "train_iters": 20000,
  "lr_decay_iters": 10000,
  "distributed_backend": "nccl",
  "lr_decay_style": "linear",
  "warmup": 0.01,
  "checkpoint_factor": 5000,
  "eval_interval": 5000,
  "eval_iters": 10,

  "log_interval": 100,
  "steps_per_print": 100,
  "wall_clock_breakdown": true,

  # additional deepspeed args not specified above
  "deepspeed_extra_args": {
    "comms_logger": {
      "enabled": true,
      "verbose": true,
      "prof_all": true,
      "debug": false
    }
  }
}
